responsive header in story mode
Smithsonian/dpo-voyager pull request #187
Opened 2023-02-15 10:06 UTC by pakrettt

The header in story mode overflow in small devices.

So I folded it by adding a scrollbar and displayed only the icons.

2023-02-15 19:31 UTC, gjcope commented
We have always considered Story to be pretty unusable on small display devices due to the complex UI and required space to work with all the features. A responsive header sounds like a step in that direction, but even with that change have you found it to be usable on small devices? How small?

2023-02-20 13:51 UTC, sdumetz commented
Without this change I have the header causing an ugly overflow as soon as I go below ~950px width.

The rest of the interface is clearly not good for mobile/small screen editing (nor does it need to be) but it remains useable for small changes even with something as small as an iPhone, which we like to be able to do when a scene needs to be fixed ASAP and we're not in the office.

There might be some more low hanging fruits there that we will contribute when we can.

2023-02-22 17:18 UTC, gjcope commented
That's fair and makes sense. With that in mind, I really like the the overflow update and the scrolling. 

I think the idea of hiding things like the logo and mode icons once the menu overflows is good but should not be based on absolute window size. A feature we are still working on is having task modes that are specific to certain user types, so they only see the features that are relevant. For instance, add &mode=qc to the end of your url and you will get a menu with less options which then overflows at a much smaller width.

2023-03-03 12:58 UTC, gjcope commented on source/client/ui/story/styles.scss
> +
Please remove - per discussion comment, this makes functional sense but should not be tied to  a specific width.

2023-03-03 13:01 UTC, gjcope requested changes
Please remove attributes tied to 'max-width'. Changing the display of these pieces makes sense, but should not be tied to width since the taskbar is variable depending on mode. Maybe an IntersectionObserver?

2023-03-16 18:15 UTC, gjcope commented
I would love to include this style change in the next release if the change request can be made so you can get credit.

2023-04-10 17:09 UTC, gjcope commented
@pakrettt @sdumetz Please update or I will close and include style change with a mention as credit.

2023-04-20 12:12 UTC, gjcope commented
No response so closing and added overflow update with tag @pakrettt

2023-04-20 12:12 UTC, closed without merging